name: Groupie Tracker CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Go
        uses: actions/setup-go@v5
        with:
          go-version: go.mod

      - name: Vérifier la compilation
        run: go build ./...
