name: Groupie Tracker CI

on:
  push:
    branches:
      - feature/ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Afficher le contenu du dépôt
        run: |
          pwd
          ls -la
          find . -maxdepth 2 -type f

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - run: go version

      - run: go build ./...
